name: webapi-deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: "dev, uat, staging, prod"
        required: true
        default: "dev"
      tag:
        description: "Release tag (e.g. myapp-webapi@1.2.3)"
        required: true

env:
  ENV: ${{ github.event.inputs.env || 'dev' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env || 'dev' }} # ${{ env.ENV }} not available yet
    steps:
      - name: Validate environment
        run: |
          if [[ ! "$ENV" =~ ^(dev|uat|staging|prod)$ ]]; then
            echo "Invalid environment: $ENV. Must be one of: dev, uat, staging, prod."
            exit 1
          fi
          echo "Environment validated: $ENV"

      - name: Extract tag + app
        run: |
          tag="${{ github.event.inputs.tag || github.event.release.tag_name }}"
          app="${tag%%-*}"
          echo "TAG=$tag" >> $GITHUB_ENV
          echo "APP=$app" >> $GITHUB_ENV

      - name: Download webapi artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TAG }}-webapi
          path: ./deploy/webapi

      - name: Replace appsettings.json placeholders
        run: |
          CONNECTION="${{ secrets.DB_CONNECTION }}"
          CONNECTION="${CONNECTION//\#\{ENV\}\#/${ENV}}"
          CONNECTION="${CONNECTION//\#\{AZURE_SQL_PASSWORD\}\#/${AZURE_SQL_PASSWORD}}"
          sed -i "s|#{DB_CONNECTION}#|$CONNECTION|g" ./deploy/webapi/appsettings.json
        env:
          AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP }}-api-edu-m-${{ env.ENV }}
          package: ./deploy/webapi