name: webapi-release

on:
  release:
    types: [published]

jobs:
  build:
    if: contains(github.event.release.tag_name, '-webapi@')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Extract tag + app
        run: |
          tag="${{ github.event.release.tag_name }}"
          app="${tag%%-*}"
          echo "TAG=$tag" >> $GITHUB_ENV
          echo "APP=$app" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore unit tests
        run: dotnet restore ./"$APP"/"$APP".tests/"$APP".tests.csproj

      - name: Build unit tests
        run: dotnet build ./"$APP"/"$APP".tests/"$APP".tests.csproj --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test ./"$APP"/"$APP".tests/"$APP".tests.csproj --configuration Release --no-build --verbosity normal

      - name: Restore webapi tests
        run: dotnet restore ./"$APP"/"$APP".webapi.tests/"$APP".webapi.tests.csproj

      - name: Build webapi tests
        run: dotnet build ./"$APP"/"$APP".webapi.tests/"$APP".webapi.tests.csproj --configuration Release --no-restore

      - name: Run webapi tests
        run: dotnet test ./"$APP"/"$APP".webapi.tests/"$APP".webapi.tests.csproj --configuration Release --no-build --verbosity normal

      - name: Restore webapi
        run: dotnet restore ./"$APP"/"$APP".webapi/"$APP".webapi.csproj

      - name: Build webapi
        run: dotnet build ./"$APP"/"$APP".webapi/"$APP".webapi.csproj --configuration Release --no-restore

      - name: Publish webapi
        run: dotnet publish ./"$APP"/"$APP".webapi/"$APP".webapi.csproj -c Release -o ./publish/webapi --no-build

      - name: Restore migrations
        run: dotnet restore ./"$APP"/"$APP".migrations/"$APP".migrations.csproj

      - name: Build migrations
        run: dotnet build ./"$APP"/"$APP".migrations/"$APP".migrations.csproj --configuration Release --no-restore

      - name: Publish migrations
        run: dotnet publish ./"$APP"/"$APP".migrations/"$APP".migrations.csproj -c Release -o ./publish/migrations --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.release.tag_name }}
          path: ./publish

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, uat]
    environment: ${{ matrix.env }}
    steps:
      - name: Extract tag + app
        run: |
          tag="${{ github.event.release.tag_name }}"
          app="${tag%%-*}"
          echo "TAG=$tag" >> $GITHUB_ENV
          echo "APP=$app" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TAG }}
          path: ./deploy

      - name: Replace appsettings.json placeholders
        run: |
          # -------------------------
          # Database connection
          # -------------------------
          CONNECTION="${{ secrets.DB_CONNECTION }}"
          CONNECTION="${CONNECTION//\#\{ENV\}\#/${{ matrix.env }}}"
          CONNECTION="${CONNECTION//\#\{AZURE_SQL_PASSWORD\}\#/${AZURE_SQL_PASSWORD}}"
          sed -i "s|#{DB_CONNECTION}#|$CONNECTION|g" ./deploy/webapi/appsettings.json
          sed -i "s|#{DB_CONNECTION}#|$CONNECTION|g" ./deploy/migrations/appsettings.json

          # -------------------------
          # Redis connection
          # -------------------------
          REDIS_CONNECTION="${{ secrets.REDIS_CONNECTION }}"
          REDIS_CONNECTION="${REDIS_CONNECTION//\#\{ENV\}\#/${{ matrix.env }}}"
          REDIS_CONNECTION="${REDIS_CONNECTION//\#\{REDIS_PASSWORD\}\#/${REDIS_PASSWORD}}"
          sed -i "s|#{REDIS_CONNECTION}#|$REDIS_CONNECTION|g" ./deploy/webapi/appsettings.json

          # -------------------------
          # Azure Monitor (OpenTelemetry)
          # -------------------------
          AZURE_MONITOR_CONNECTION="${{ secrets.AZURE_MONITOR_CONNECTION }}"
          sed -i "s|#{AZURE_MONITOR_CONNECTION}#|$AZURE_MONITOR_CONNECTION|g" ./deploy/webapi/appsettings.json
          sed -i "s|#{AZURE_MONITOR_CONNECTION}#|$AZURE_MONITOR_CONNECTION|g" ./deploy/migrations/appsettings.json
        env:
          AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

      - name: Execute migrations
        run: dotnet ./deploy/migrations/$APP.migrations.dll --env ${{ matrix.env }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP }}-api-edu-m-${{ matrix.env }}
          package: ./deploy/webapi