name: webapi-release

on:
  release:
    types: [published]

jobs:
  build:
    if: contains(github.event.release.tag_name, '-webapi@')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Extract tag + app
        run: |
          tag="${{ github.event.release.tag_name }}"
          app="${tag%%-*}"
          echo "TAG=$tag" >> $GITHUB_ENV
          echo "APP=$app" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore tests
        run: dotnet restore ./"$APP"/"$APP".tests/"$APP".tests.csproj

      - name: Build tests
        run: dotnet build ./"$APP"/"$APP".tests/"$APP".tests.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./"$APP"/"$APP".tests/"$APP".tests.csproj --configuration Release --no-build --verbosity normal

      - name: Restore webapi
        run: dotnet restore ./"$APP"/"$APP".webapi/"$APP".webapi.csproj

      - name: Build webapi
        run: dotnet build ./"$APP"/"$APP".webapi/"$APP".webapi.csproj --configuration Release --no-restore

      - name: Publish webapi
        run: dotnet publish ./"$APP"/"$APP".webapi/"$APP".webapi.csproj -c Release -o ./publish/webapi --no-build

      - name: Upload webapi artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.release.tag_name }}-webapi
          path: ./publish/webapi